pong-a3c-stable:
    env: BreakoutDeterministic-v4
    run: A3C
    repeat: 2
    resources:
        cpu: 9
        driver_cpu_limit: 1
    stop:
        episode_reward_mean: 10
        training_iteration: 150
    config:
        num_workers: 8
        queue_size:
            grid_search: [1, 2]
        batch_size:
            grid_search: [10, 15, 25, 50]
        use_lstm: true
        use_pytorch: false
        vf_loss_coeff: 0.5
        entropy_coeff: -0.01
        gamma: 0.99
        grad_clip:
            grid_search: [0.1, 1.0, 5.0, 10.0]
        lambda: 1.0
        lr: 0.0001
        observation_filter: NoFilter
        reward_filter: NoFilter
        model:
            channel_major: false
            dim: 42
            grayscale: true
            zero_mean: false
        optimizer:
            grads_per_step: 1000
